services:
  banking-app:
    build: .
    image: banking
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:        # <-- Add this line
      - .env         # <-- Add this line
    restart: "no"