# Generated by Django 6.0.3 on 2026-04-18 19:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0006_account_account_type_account_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('merchant_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reason_flag', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guardian_notes', models.TextField(blank=True)),
                ('account_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_transactions', to=settings.AUTH_USER_MODEL)),
                ('guardian', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_assigned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SafeSpendLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_limit', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('daily_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_reset_date', models.DateField(default=django.utils.timezone.now)),
                ('allow_late_night', models.BooleanField(default=False)),
                ('quiet_hours_start', models.IntegerField(default=22, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('quiet_hours_end', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('account_holder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='safe_spend', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_guardian', models.BooleanField(default=False)),
                ('is_account_holder', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('managed_accounts', models.ManyToManyField(blank=True, limit_choices_to={'profile__is_account_holder': True}, related_name='guardians', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='MerchantWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('rule_type', models.CharField(choices=[('allow', 'Always Allow'), ('block', 'Always Block'), ('require_approval', 'Require Guardian Review')], default='require_approval', max_length=20)),
                ('account_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelist_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('account_holder', 'merchant_name')},
            },
        ),
    ]
