# Generated by Django 6.0.4 on 2026-04-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0007_pendingtransaction_safespendlimit_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingtransaction',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='gateway_response',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='payment_status',
            field=models.CharField(default='local_pending', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='gateway_response',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='merchant_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_status',
            field=models.CharField(default='local_processed', max_length=50),
        ),
    ]
